spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.21.247:3306/start?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: rw_user
    password: bbs@12345678

